mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://47.95.141.31/prevention?characterEncoding=utf-8
  jackson:
    time-zone: GMT+8
logging:
  config: classpath:log4j2.xml
